apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
spec:
  selector:
    matchLabels:
      run: frontend1
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend1
    spec:
      containers:
      - name: frontend1
        image: docker.io/doctorcodes/udagram-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m


---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: frontend
